### ISSUE TITLE
Slide accepting pathlib.Path as path of slide on disk

### ISSUE THREAD

**Issue by alessiamarcolini** [histolab/histolab#225]
OpenSlide only supports `str` as for path slides, but on our side we could accept `pathlib.Path` as well and convert it to `str` internally.

**Comment by lorenz-gorini** [comment]
I have to say that when I encountered the related error, it was quite hard to understand its message and its origin, because of the laziness of `Slide._wsi` property.
Maybe it could be useful to catch exceptions like this from `openslide.open_slide` function ([here](https://github.com/histolab/histolab/blob/6febdd858c933157e8cf5d6dea72982fcbecf6d5/src/histolab/slide.py#L530)) in order to tell the user that the slide path was not correct?

By the way, I opened an issue in `openslide-python` because I think it is more related to them https://github.com/openslide/openslide-python/issues/112

**Comment by alessiamarcolini** [comment]
Thank you @lorenz-gorini for opening the issue on the Openslide repo. 
Anyway, now the fix for pathlib on our side is done and waiting to be merged 😃
