### ISSUE TITLE
Matter regions ignored by tiling with check_tissue=True

### ISSUE THREAD

**Issue by jeandut** [histolab/histolab#417]
**Describe the bug**
The tiling with check_tissue=True option is failing in a dramatic fashion on some easy examples of a standard dataset Camelyon16. The appearance of the errors seem to indicate a mistake on the total surface checked for tissues on the slide. However it does not always happen only some images have this behavior.

**To Reproduce**
1. Download the Camelyon16 slides Normal_015.tif and Normal_014.tif from https://drive.google.com/drive/folders/0BzsdkU4jWx9BNUFqRE81QS04eDg?resourcekey=0-p6LFOzRfCTfyi_JpshhoTQ
2. Install openslide, histolab and large image
3. Execute the following code:
```python
    from histolab.slide import Slide
    from histolab.tiler import GridTiler
    grid_tiles_extractor = GridTiler(
        tile_size=(224, 224),
        level=1,
        pixel_overlap=0,
        prefix="grid/",
        check_tissue=True,
        suffix=".png",
    )
    slide = Slide("Normal_014.tif, "./tmp", use_largeimage=True)
    histolab_tiling = grid_tiles_extractor.locate_tiles(
        slide=slide,
        scale_factor=64,
        alpha=0,
        outline="#046C4C",
    )
    histolab_tiling.save("bug.png")
```

**Expected behavior**

All matter regions should be tiled.

**Screenshots**
<img width="811" alt="Capture d’écran 2022-06-21 à 12 00 58" src="https://user-images.githubusercontent.com/11030901/174773489-9864fa68-5cc2-4acb-a0b7-183dc281ca1f.png">
<img width="682" alt="Capture d’écran 2022-06-21 à 12 01 41" src="https://user-images.githubusercontent.com/11030901/174773612-efd72213-cb57-4d5e-a173-d7b1c3e4dad8.png">

**Software (please complete the following information):**
 - OS: Tested on Ubuntu 20.04
 - Python Version: 3.8.13
 - histolab version: 0.4.0

**Comment by alessiamarcolini** [comment]
Dear @jeandut thank you for opening this issue.

The result you're showing is compatible with the default tiling behavior, i.e., extracting tiles from the biggest tissue portion in the slide. This behavior is controlled by the parameter `extraction_mask` in the `locate_tiles` or `extract` method of the tiler, which has `histolab.masks.BiggestTissueBoxMask()` as default value.

Therefore, if you want to extract tiles from all the tissue found in the slide you need to instantiate the `histolab.masks.TissueMask` extraction mask and pass it to `extraction_mask`.

```python
from histolab.masks import TissueMask

# your code here

histolab_tiling = grid_tiles_extractor.locate_tiles(
        slide=slide,
        extraction_mask=TissueMask(),
        scale_factor=64,
        alpha=0,
        outline="#046C4C",
    )
```

P.S.: The decision to have `BiggestTissueBoxMask` as the default value is due to retro-compatibility with older projects using alpha versions of histolab, but we can definitely discuss if it still makes sense now that the project is a bit more mature. cc @ernestoarbitrio @nicolebussola

**Comment by alessiamarcolini** [comment]
Hi @jeandut, actually we wrote this tutorial to clarify this behavior https://histolab.readthedocs.io/en/latest/tissue_masks.html

But maybe it's not clear enough!! Thank you for reaching out :)
