### ISSUE TITLE
.locate_mask fails silently

### ISSUE THREAD

**Issue by OncologyDS** [histolab/histolab#431]
**Describe the bug**
The .locate_mask command fails when run on local data. This is despite working if I run the example : https://histolab.readthedocs.io/en/latest/tissue_masks.html. 

**To Reproduce**

The below is the code that fails
`
from histolab.slide import Slide
from histolab.masks import TissueMask
from histolab.filters.image_filters import (
    BluePenFilter,
    GreenPenFilter,
    ApplyMaskImage,
    Invert,
    OtsuThreshold,
    RgbToGrayscale
)
from histolab.filters.morphological_filters import (
    RemoveSmallHoles,
    RemoveSmallObjects
)
import os
import glob

#0. declare Test slides
blue_pen_markings = [
    "slide_name"
]

#1. Declare paths
base_path = "base_path"

blue_pen_fullpath = glob.glob(os.path.join(base_path,blue_pen_markings[0],"*"))
slide_processed_path = os.path.join(blue_pen_fullpath[0], 'processed')
print(blue_pen_fullpath)

#2. create slide object and do checks - all good
attune_slide = Slide(blue_pen_fullpath[0], processed_path=slide_processed_path)
print(f"Slide name: {attune_slide.name}")
print(f"Levels: {attune_slide.levels}")
print(f"Dimensions at level 0: {attune_slide.dimensions}")
print(f"Dimensions at level 1: {attune_slide.level_dimensions(level=1)}")
print(f"Dimensions at level 2: {attune_slide.level_dimensions(level=2)}")

#3. look at slide - this works
attune_slide.thumbnail
attune_slide.show()

#4. create mask object
mask = TissueMask()

#5. print mask - this fails - no mask is shown 
attune_slide.locate_mask(custom_mask)

#6. This will still print
print("success")

`

**Expected behavior**
I expect locate mask to show an image of the resulting mask overlaid on the slide, or to give an error warning. Instead, no image is shown and the next bit of code still runs.

**Software (please complete the following information):**
 - OS: Linux 3.10.0-1160.11.1.el7.x86_64
 - Python Version: 3.9.12
 - histolab version: 0.5.1
 - openslide version: 3.4.1
 - pillow version: 8.4.0

**Additional context**
If I run the test case from histolab I do not encounter this problem, which suggests to me that something is happening with regards to the images themselves. The .thumbnail and .show commands still work, so histolab does manage to import the images and show the initial details. 

I appreciate this will probably be difficult to solve since it appears to be an image-based problem, but some guidance debugging this would still be appreciated if possible.

**Comment by alessiamarcolini** [comment]
Dear @OncologyDS, thank you for opening this issue.

From the code snippet you posted, I can understand that you are calculating the `locate_mask` result but you are not storing it anywhere and so the value gets lost. This is because that method returns a PIL image, it doesn't show it automatically. If you run this code in a Jupyter notebook cell-by-cell, you will see the result, but if you run this as a script you won't.

If you still want to run this as a script you can do

```python
mask_location = attune_slide.locate_mask(custom_mask)
mask_location.show()
```

I hope this makes sense! :) 

PS next time please format your markdown text to highlight your code, so it's easier to read :) you can find more information [here](https://bayergroup.sharepoint.com/:p:/r/sites/InternsatBayerGermany/Shared%20Documents/General/Guide%20Berlin%20Interns_Feb2021.pptx?d=w75116081713c4e7f8dcc275027a1db0b&csf=1&web=1)

**Comment by OncologyDS** [comment]
Dear @alessiamarcolini,

Thank you so much for the prompt reply. Indeed, storing the mask then using show worked. I should have thought of that! I'm confused as to why that's not needed in the test case but is for this.

I will have a read of those rules and try and format the code appropriately, it is indeed hard to read.

Hope you have a nice day.
